/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

import java.util.ArrayList;
import java.util.Collections;

//if divisable by 3 fizz
// if divisable by 5 buzz
/// if divisable by 3 + 5 then fizzbuzz
// if divisable by 7 then bang
// if divisable by 11 then bong

//First Check if divisable by 11 and if so print bang
//Then Check if its divisable by 7 and 5 or 7 and 3 but 
public class App {
    
    public static void fizzbuzz() {
        String cleanOut;
        for (int i = 1; i < 300; i++) {
            cleanOut = "";
            ArrayList<String> output = new ArrayList<>();
            if (isDivBy(i, 3)) {
                output.add("Fizz");
            }
            if (isDivBy(i, 13)) {
                output.add("Fezz");
            }
            if (isDivBy(i, 5)) {
                output.add("Buzz");
            }
            if (isDivBy(i, 7)) {
                output.add("Bang");
            }
            if (isDivBy(i, 11)) {
                if(isDivBy(i, 13))
                {
                    output.clear();
                    output.add("Fezz");
                    output.add("Bong");
                }
                else{
                    output.add("Bong");
                }
                
            }
            if(isDivBy(i, 17))
            {
             Collections.reverse(output);   
            }

            if (output.size() == 0) 
            {
                output.add(Integer.toString(i));
            }

            for(int y = 0; y < output.size(); y++)
            {
                cleanOut += output.get(y);
            }
               
            System.out.println(cleanOut); 
            
            
        }

    }

    public static boolean isDivBy(int i, int divNum) {
        // checking if int i is divisable by int divNum
        return i % divNum == 0;
    }

    public static void main(String[] args) {
        fizzbuzz();
    }
}
